services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${PG_CONTAINER_IMAGE}
    container_name: ${PG_CONTAINER_NAME}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: ${PGDATA}
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - fastdash_volume:/data/fastdash_container
volumes:
    fastdash_volume:
      external: true